spring:
  application:
    name: cards-service
  datasource:
    url: jdbc:h2:mem:accountservicedb
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 9000
logging:
  level:
    org.springframework: INFO
    org.sumeet.account: DEBUG
build:
  version: 3.0.0
cards:
  message: "Welcome to DemoBank cards related local APIs "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@demobank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932